import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Background from './components/Background';
import Navbar from './components/Navbar';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import MarginComponent from './components/MarginComponent';
import Topbar from './components/Topbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background />
        <Navbar />
        <MarginComponent />
        <Topbar />
        {children}
      </body>
    </html>
  );
}
